// Test data generator for the new property structure
export const generateTestProperties = () => {
  return [
    {
      address: '123 Main Street, Downtown, CA 90210',
      nickname: 'Downtown Office Complex',
      type: 'Commercial',
      status: 'Available',
      spec: {
        type: 'Office Building',
        story: 5,
        bedroom: 0,
        full_bathroom: 8,
        kitchen: 2,
        meeting_room: 12,
        office: 25,
        half_bathroom: 4,
        garage: 50,
        size: 25000,
        lot_size: 15000,
        hoa_name: 'Downtown Business Association',
        hoa_contact: 'contact@downtownba.com',
      },
      equipments: [
        {
          status: 'Active',
          category: 'HVAC',
          Name: 'Central Air System',
          Manufacture: 'Carrier',
          Model: '48TC',
          Serial: 'CRR-2023-001',
          Manufactured_year: 2023,
          Purchased_year: 2023,
          Warranty_length: '5 years',
          Invoice_price: 15000,
        },
        {
          status: 'Active',
          category: 'Security',
          Name: 'Access Control System',
          Manufacture: 'Honeywell',
          Model: 'HID-5000',
          Serial: 'HNY-2023-002',
          Manufactured_year: 2023,
          Purchased_year: 2023,
          Warranty_length: '3 years',
          Invoice_price: 8000,
        },
      ],
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-01-15'),
    },
    {
      address: '456 Oak Avenue, Suburbia, CA 90211',
      nickname: 'Family Home',
      type: 'Residential',
      status: 'Available',
      spec: {
        type: 'Single Family',
        story: 2,
        bedroom: 4,
        full_bathroom: 3,
        kitchen: 1,
        meeting_room: 0,
        office: 1,
        half_bathroom: 1,
        garage: 2,
        size: 2800,
        lot_size: 8000,
        hoa_name: 'Oak Grove HOA',
        hoa_contact: 'info@oakgrovehoa.com',
      },
      equipments: [
        {
          status: 'Active',
          category: 'Appliances',
          Name: 'Refrigerator',
          Manufacture: 'Samsung',
          Model: 'RF28T5000SR',
          Serial: 'SMS-2022-001',
          Manufactured_year: 2022,
          Purchased_year: 2022,
          Warranty_length: '2 years',
          Invoice_price: 1200,
        },
        {
          status: 'Active',
          category: 'HVAC',
          Name: 'Furnace',
          Manufacture: 'Trane',
          Model: 'S9X2',
          Serial: 'TRN-2021-001',
          Manufactured_year: 2021,
          Purchased_year: 2021,
          Warranty_length: '10 years',
          Invoice_price: 4500,
        },
      ],
      createdAt: new Date('2024-02-20'),
      updatedAt: new Date('2024-02-20'),
    },
    {
      address: '789 Industrial Blvd, Factory District, CA 90212',
      nickname: 'Warehouse Complex',
      type: 'Industrial',
      status: 'Under Contract',
      spec: {
        type: 'Warehouse',
        story: 1,
        bedroom: 0,
        full_bathroom: 2,
        kitchen: 1,
        meeting_room: 2,
        office: 3,
        half_bathroom: 0,
        garage: 0,
        size: 50000,
        lot_size: 75000,
        hoa_name: 'Industrial Park Association',
        hoa_contact: 'admin@industrialpark.com',
      },
      equipments: [
        {
          status: 'Active',
          category: 'Loading Equipment',
          Name: 'Forklift',
          Manufacture: 'Toyota',
          Model: '8FGCU25',
          Serial: 'TYT-2022-001',
          Manufactured_year: 2022,
          Purchased_year: 2022,
          Warranty_length: '3 years',
          Invoice_price: 25000,
        },
        {
          status: 'Maintenance',
          category: 'Security',
          Name: 'Surveillance System',
          Manufacture: 'Dahua',
          Model: 'NVR-16',
          Serial: 'DHU-2023-001',
          Manufactured_year: 2023,
          Purchased_year: 2023,
          Warranty_length: '2 years',
          Invoice_price: 3500,
        },
      ],
      createdAt: new Date('2024-03-10'),
      updatedAt: new Date('2024-03-10'),
    },
    {
      address: '321 Beach Road, Coastal City, CA 90213',
      nickname: 'Beach Condo',
      type: 'Residential',
      status: 'Sold',
      spec: {
        type: 'Condo',
        story: 8,
        bedroom: 2,
        full_bathroom: 2,
        kitchen: 1,
        meeting_room: 0,
        office: 0,
        half_bathroom: 1,
        garage: 1,
        size: 1200,
        lot_size: 0,
        hoa_name: 'Beachfront Condo Association',
        hoa_contact: 'hoa@beachfrontcondo.com',
      },
      equipments: [
        {
          status: 'Active',
          category: 'Appliances',
          Name: 'Dishwasher',
          Manufacture: 'Bosch',
          Model: 'SHEM63W55N',
          Serial: 'BSC-2023-001',
          Manufactured_year: 2023,
          Purchased_year: 2023,
          Warranty_length: '2 years',
          Invoice_price: 800,
        },
      ],
      createdAt: new Date('2024-01-05'),
      updatedAt: new Date('2024-01-05'),
    },
    {
      address: '654 Mountain View Drive, Hillside, CA 90214',
      nickname: 'Mountain Retreat',
      type: 'Residential',
      status: 'Available',
      spec: {
        type: 'Single Family',
        story: 3,
        bedroom: 5,
        full_bathroom: 4,
        kitchen: 2,
        meeting_room: 1,
        office: 2,
        half_bathroom: 2,
        garage: 3,
        size: 4500,
        lot_size: 15000,
        hoa_name: 'Mountain View Estates',
        hoa_contact: 'info@mountainviewestates.com',
      },
      equipments: [
        {
          status: 'Active',
          category: 'Entertainment',
          Name: 'Home Theater System',
          Manufacture: 'Sony',
          Model: 'STR-DN1080',
          Serial: 'SNY-2023-001',
          Manufactured_year: 2023,
          Purchased_year: 2023,
          Warranty_length: '1 year',
          Invoice_price: 1800,
        },
        {
          status: 'Active',
          category: 'Outdoor',
          Name: 'Hot Tub',
          Manufacture: 'Jacuzzi',
          Model: 'J-385',
          Serial: 'JCZ-2022-001',
          Manufactured_year: 2022,
          Purchased_year: 2022,
          Warranty_length: '5 years',
          Invoice_price: 12000,
        },
      ],
      createdAt: new Date('2024-04-01'),
      updatedAt: new Date('2024-04-01'),
    },
  ]
}

export const generateTestMxRecords = () => {
  return [
    {
      property_id: 'property1',
      mx_id: 'mx_1705276800000',
      create_id: 'user1',
      reported_by: 'John Smith',
      reported_role: 'Property Manager',
      description: 'DNS resolution issues affecting email delivery',
      create_timestamp: new Date('2024-01-15T10:00:00'),
      report_date: '2024-01-15',
      resolv_date: null,
      resolution: '',
      resolv_by: '',
      logs: [
        {
          log_timestamp: new Date('2024-01-15T10:00:00'),
          comment: 'Initial report submitted',
          user_id: 'user1',
          user_name: 'John Smith',
          user_role: 'Property Manager',
        },
      ],
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-01-15'),
    },
    {
      property_id: 'property2',
      mx_id: 'mx_1708454400000',
      create_id: 'user2',
      reported_by: 'Sarah Johnson',
      reported_role: 'Landlord',
      description: 'MX record priority needs adjustment for load balancing',
      create_timestamp: new Date('2024-02-20T14:30:00'),
      report_date: '2024-02-20',
      resolv_date: new Date('2024-02-21T09:15:00'),
      resolution: 'Priority adjusted from 10 to 5 for better load balancing',
      resolv_by: 'Mike Tech',
      logs: [
        {
          log_timestamp: new Date('2024-02-20T14:30:00'),
          comment: 'Report submitted for MX record optimization',
          user_id: 'user2',
          user_name: 'Sarah Johnson',
          user_role: 'Landlord',
        },
        {
          log_timestamp: new Date('2024-02-21T09:15:00'),
          comment: 'Working on priority adjustment',
          user_id: 'user3',
          user_name: 'Mike Tech',
          user_role: 'IT Support',
        },
        {
          log_timestamp: new Date('2024-02-21T09:15:00'),
          comment: 'Issue resolved - priority adjusted successfully',
          user_id: 'user3',
          user_name: 'Mike Tech',
          user_role: 'IT Support',
        },
      ],
      createdAt: new Date('2024-02-20'),
      updatedAt: new Date('2024-02-21'),
    },
  ]
}

export const generateTestUserRoles = () => {
  return [
    {
      property_id: 'property1',
      user_id: 'user1',
      role: 'Property Manager',
      role_date: '2024-01-01',
      expire_date: '',
      role_grant_by: 'System',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      property_id: 'property2',
      user_id: 'user2',
      role: 'Landlord',
      role_date: '2024-01-01',
      expire_date: '',
      role_grant_by: 'System',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      property_id: 'property3',
      user_id: 'user3',
      role: 'Property Manager',
      role_date: '2024-02-01',
      expire_date: '',
      role_grant_by: 'System',
      createdAt: new Date('2024-02-01'),
      updatedAt: new Date('2024-02-01'),
    },
    {
      property_id: 'property4',
      user_id: 'user4',
      role: 'Landlord',
      role_date: '2024-01-01',
      expire_date: '',
      role_grant_by: 'System',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      property_id: 'property5',
      user_id: 'user5',
      role: 'Property Manager',
      role_date: '2024-03-01',
      expire_date: '',
      role_grant_by: 'System',
      createdAt: new Date('2024-03-01'),
      updatedAt: new Date('2024-03-01'),
    },
  ]
}

export const generateTestUserProfiles = () => {
  return [
    {
      user_id: 'user1',
      user_name: 'John Smith',
      first_name: 'John',
      last_name: 'Smith',
      middle_name: '',
      cellphone: '+1-555-0101',
      email: 'john.smith@example.com',
      roles: [],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      user_id: 'user2',
      user_name: 'Sarah Johnson',
      first_name: 'Sarah',
      last_name: 'Johnson',
      middle_name: '',
      cellphone: '+1-555-0102',
      email: 'sarah.johnson@example.com',
      roles: [],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      user_id: 'user3',
      user_name: 'Mike Tech',
      first_name: 'Mike',
      last_name: 'Tech',
      middle_name: '',
      cellphone: '+1-555-0103',
      email: 'mike.tech@example.com',
      roles: [],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
  ]
}
