// Test data generator for the new property structure
export const generateTestProperties = () => {
  return [
    {
      address: '123 Main Street, Downtown, CA 90210',
      nickname: 'Downtown Office Complex',
      type: 'Commercial',
      status: 'Available',
      spec: {
        type: 'Office Building',
        story: 5,
        bedroom: 0,
        full_bathroom: 8,
        kitchen: 2,
        meeting_room: 12,
        office: 25,
        half_bathroom: 4,
        garage: 50,
        size: 25000,
        lot_size: 15000,
        hoa_name: 'Downtown Business Association',
        hoa_contact: 'contact@downtownba.com',
      },
      equipments: [
        {
          status: 'Active',
          category: 'HVAC',
          Name: 'Central Air System',
          Manufacture: 'Carrier',
          Model: '48TC',
          Serial: 'CRR-2023-001',
          Manufactured_year: 2023,
          Purchased_year: 2023,
          Warranty_length: '5 years',
          Invoice_price: 15000,
        },
        {
          status: 'Active',
          category: 'Security',
          Name: 'Access Control System',
          Manufacture: 'Honeywell',
          Model: 'HID-5000',
          Serial: 'HNY-2023-002',
          Manufactured_year: 2023,
          Purchased_year: 2023,
          Warranty_length: '3 years',
          Invoice_price: 8000,
        },
      ],
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-01-15'),
    },
    {
      address: '456 Oak Avenue, Suburbia, CA 90211',
      nickname: 'Family Home',
      type: 'Residential',
      status: 'Available',
      spec: {
        type: 'Single Family',
        story: 2,
        bedroom: 4,
        full_bathroom: 3,
        kitchen: 1,
        meeting_room: 0,
        office: 1,
        half_bathroom: 1,
        garage: 2,
        size: 2800,
        lot_size: 8000,
        hoa_name: 'Oak Grove HOA',
        hoa_contact: 'info@oakgrovehoa.com',
      },
      equipments: [
        {
          status: 'Active',
          category: 'Appliances',
          Name: 'Refrigerator',
          Manufacture: 'Samsung',
          Model: 'RF28T5000SR',
          Serial: 'SMS-2022-001',
          Manufactured_year: 2022,
          Purchased_year: 2022,
          Warranty_length: '2 years',
          Invoice_price: 1200,
        },
        {
          status: 'Active',
          category: 'HVAC',
          Name: 'Furnace',
          Manufacture: 'Trane',
          Model: 'S9X2',
          Serial: 'TRN-2021-001',
          Manufactured_year: 2021,
          Purchased_year: 2021,
          Warranty_length: '10 years',
          Invoice_price: 4500,
        },
      ],
      createdAt: new Date('2024-02-20'),
      updatedAt: new Date('2024-02-20'),
    },
    {
      address: '789 Industrial Blvd, Factory District, CA 90212',
      nickname: 'Warehouse Complex',
      type: 'Industrial',
      status: 'Under Contract',
      spec: {
        type: 'Warehouse',
        story: 1,
        bedroom: 0,
        full_bathroom: 2,
        kitchen: 1,
        meeting_room: 2,
        office: 3,
        half_bathroom: 0,
        garage: 0,
        size: 50000,
        lot_size: 75000,
        hoa_name: 'Industrial Park Association',
        hoa_contact: 'admin@industrialpark.com',
      },
      equipments: [
        {
          status: 'Active',
          category: 'Loading Equipment',
          Name: 'Forklift',
          Manufacture: 'Toyota',
          Model: '8FGCU25',
          Serial: 'TYT-2022-001',
          Manufactured_year: 2022,
          Purchased_year: 2022,
          Warranty_length: '3 years',
          Invoice_price: 25000,
        },
        {
          status: 'Maintenance',
          category: 'Security',
          Name: 'Surveillance System',
          Manufacture: 'Dahua',
          Model: 'NVR-16',
          Serial: 'DHU-2023-001',
          Manufactured_year: 2023,
          Purchased_year: 2023,
          Warranty_length: '2 years',
          Invoice_price: 3500,
        },
      ],
      createdAt: new Date('2024-03-10'),
      updatedAt: new Date('2024-03-10'),
    },
    {
      address: '321 Beach Road, Coastal City, CA 90213',
      nickname: 'Beach Condo',
      type: 'Residential',
      status: 'Sold',
      spec: {
        type: 'Condo',
        story: 8,
        bedroom: 2,
        full_bathroom: 2,
        kitchen: 1,
        meeting_room: 0,
        office: 0,
        half_bathroom: 1,
        garage: 1,
        size: 1200,
        lot_size: 0,
        hoa_name: 'Beachfront Condo Association',
        hoa_contact: 'hoa@beachfrontcondo.com',
      },
      equipments: [
        {
          status: 'Active',
          category: 'Appliances',
          Name: 'Dishwasher',
          Manufacture: 'Bosch',
          Model: 'SHEM63W55N',
          Serial: 'BSC-2023-001',
          Manufactured_year: 2023,
          Purchased_year: 2023,
          Warranty_length: '2 years',
          Invoice_price: 800,
        },
      ],
      createdAt: new Date('2024-01-05'),
      updatedAt: new Date('2024-01-05'),
    },
    {
      address: '654 Mountain View Drive, Hillside, CA 90214',
      nickname: 'Mountain Retreat',
      type: 'Residential',
      status: 'Available',
      spec: {
        type: 'Single Family',
        story: 3,
        bedroom: 5,
        full_bathroom: 4,
        kitchen: 2,
        meeting_room: 1,
        office: 2,
        half_bathroom: 2,
        garage: 3,
        size: 4500,
        lot_size: 15000,
        hoa_name: 'Mountain View Estates',
        hoa_contact: 'info@mountainviewestates.com',
      },
      equipments: [
        {
          status: 'Active',
          category: 'Entertainment',
          Name: 'Home Theater System',
          Manufacture: 'Sony',
          Model: 'STR-DN1080',
          Serial: 'SNY-2023-001',
          Manufactured_year: 2023,
          Purchased_year: 2023,
          Warranty_length: '1 year',
          Invoice_price: 1800,
        },
        {
          status: 'Active',
          category: 'Outdoor',
          Name: 'Hot Tub',
          Manufacture: 'Jacuzzi',
          Model: 'J-385',
          Serial: 'JCZ-2022-001',
          Manufactured_year: 2022,
          Purchased_year: 2022,
          Warranty_length: '5 years',
          Invoice_price: 12000,
        },
      ],
      createdAt: new Date('2024-04-01'),
      updatedAt: new Date('2024-04-01'),
    },
  ]
}

export const generateTestMxRecords = () => {
  return [
    {
      property_id: 'property1',
      mx_id: 'mx_1705276800000',
      create_id: 'user1',
      reported_by: 'John Smith',
      reported_role: 'Property Manager',
      description: 'DNS resolution issues affecting email delivery',
      create_timestamp: new Date('2024-01-15T10:00:00'),
      report_date: '2024-01-15',
      resolv_date: null,
      resolution: '',
      resolv_by: '',
      logs: [
        {
          log_timestamp: new Date('2024-01-15T10:00:00'),
          comment: 'Initial report submitted',
          user_id: 'user1',
          user_name: 'John Smith',
          user_role: 'Property Manager',
        },
      ],
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-01-15'),
    },
    {
      property_id: 'property2',
      mx_id: 'mx_1708454400000',
      create_id: 'user2',
      reported_by: 'Sarah Johnson',
      reported_role: 'Property Owner',
      description: 'Task priority needs adjustment for load balancing',
      create_timestamp: new Date('2024-02-20T14:30:00'),
      report_date: '2024-02-20',
      resolv_date: new Date('2024-02-21T09:15:00'),
      resolution: 'Priority adjusted from 10 to 5 for better load balancing',
      resolv_by: 'Mike Tech',
      logs: [
        {
          log_timestamp: new Date('2024-02-20T14:30:00'),
          comment: 'Report submitted for task optimization',
          user_id: 'user2',
          user_name: 'Sarah Johnson',
          user_role: 'Property Owner',
        },
        {
          log_timestamp: new Date('2024-02-21T09:15:00'),
          comment: 'Working on priority adjustment',
          user_id: 'user3',
          user_name: 'Mike Tech',
          user_role: 'IT Support',
        },
        {
          log_timestamp: new Date('2024-02-21T09:15:00'),
          comment: 'Issue resolved - priority adjusted successfully',
          user_id: 'user3',
          user_name: 'Mike Tech',
          user_role: 'IT Support',
        },
      ],
      createdAt: new Date('2024-02-20'),
      updatedAt: new Date('2024-02-21'),
    },
  ]
}

export const generateTestUserRoles = () => {
  return [
    {
      property_id: 'property1',
      user_id: 'user1',
      role: 'Property Manager',
      role_date: '2024-01-01',
      expire_date: '',
      role_grant_by: 'System',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      property_id: 'property2',
      user_id: 'user2',
      role: 'Property Owner',
      role_date: '2024-01-01',
      expire_date: '',
      role_grant_by: 'System',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      property_id: 'property3',
      user_id: 'user3',
      role: 'Property Manager',
      role_date: '2024-02-01',
      expire_date: '',
      role_grant_by: 'System',
      createdAt: new Date('2024-02-01'),
      updatedAt: new Date('2024-02-01'),
    },
    {
      property_id: 'property4',
      user_id: 'user4',
      role: 'Property Owner',
      role_date: '2024-01-01',
      expire_date: '',
      role_grant_by: 'System',
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      property_id: 'property5',
      user_id: 'user5',
      role: 'Property Manager',
      role_date: '2024-03-01',
      expire_date: '',
      role_grant_by: 'System',
      createdAt: new Date('2024-03-01'),
      updatedAt: new Date('2024-03-01'),
    },
  ]
}

export const generateTestUserProfiles = () => {
  return [
    {
      user_id: 'user1',
      user_name: 'John Smith',
      first_name: 'John',
      last_name: 'Smith',
      middle_name: '',
      cellphone: '+1-555-0101',
      email: 'john.smith@example.com',
      roles: [],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      user_id: 'user2',
      user_name: 'Sarah Johnson',
      first_name: 'Sarah',
      last_name: 'Johnson',
      middle_name: '',
      cellphone: '+1-555-0102',
      email: 'sarah.johnson@example.com',
      roles: [],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    {
      user_id: 'user3',
      user_name: 'Mike Tech',
      first_name: 'Mike',
      last_name: 'Tech',
      middle_name: '',
      cellphone: '+1-555-0103',
      email: 'mike.tech@example.com',
      roles: [],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
  ]
}

export const generateTestLeases = () => {
  return [
    {
      lease_id: 'lease-1',
      property_id: 'property1',
      property_string_id: 'property1',
      tenant_id: 'user1',
      created_by: 'user2',
      rate_amount: 2400,
      rate_type: 'month',
      lease_term: 12,
      lease_start_date: '2024-01-01',
      lease_end_date: '2024-12-31',
      deposit: 2400,
      status: 'Active',
      furnished: 'No',
      pet_fee: 0,
      application_fee_per_person: 50,
      created_at: new Date('2023-12-15'),
      updated_at: new Date('2023-12-15'),
    },
    {
      lease_id: 'lease-2',
      property_id: 'property2',
      property_string_id: 'property2',
      tenant_id: 'user3',
      created_by: 'user2',
      rate_amount: 3200,
      rate_type: 'month',
      lease_term: 24,
      lease_start_date: '2024-02-01',
      lease_end_date: '2026-01-31',
      deposit: 3200,
      status: 'Active',
      furnished: 'Yes',
      pet_fee: 350,
      application_fee_per_person: 75,
      created_at: new Date('2024-01-20'),
      updated_at: new Date('2024-01-20'),
    },
  ]
}

export const generateTestTransactions = () => {
  return [
    {
      transac_id: 'txn-1',
      property_id: 'property1',
      lease_id: 'lease-1',
      transac_type: 'Rent',
      amount: 2400,
      transac_date: '2024-01-05',
      transac_from: 'Tenant',
      transac_to: 'Property Owner',
      role: 'Landlord',
      created_by: 'user2',
      created_datetime: new Date('2024-01-05T10:00:00'),
    },
    {
      transac_id: 'txn-2',
      property_id: 'property1',
      lease_id: '',
      transac_type: 'HOA Fee',
      amount: 500,
      transac_date: '2024-01-15',
      transac_from: 'Property Owner',
      transac_to: 'HOA',
      role: 'Landlord',
      created_by: 'user2',
      created_datetime: new Date('2024-01-15T09:00:00'),
    },
    {
      transac_id: 'txn-3',
      property_id: 'property1',
      lease_id: 'lease-1',
      transac_type: 'Maintenance',
      amount: -350,
      transac_date: '2024-01-20',
      transac_from: 'Property Owner',
      transac_to: 'Vendor',
      role: 'Landlord',
      created_by: 'user2',
      created_datetime: new Date('2024-01-20T14:30:00'),
    },
  ]
}

export const generateTestReminders = () => {
  return [
    {
      reminder_id: 'rem-1',
      property_id: 'property1',
      category: 'fee',
      note: 'HOA payment due',
      amount: 500,
      start_date: '2024-02-01',
      repeat_by: 'monthly',
      status: true,
      created_by: 'user2',
      created_date: new Date('2024-01-15'),
    },
    {
      reminder_id: 'rem-2',
      property_id: 'property1',
      category: 'lease',
      note: 'Lease renewal discussion',
      amount: 0,
      start_date: '2024-11-01',
      repeat_by: 'once',
      status: true,
      created_by: 'user2',
      created_date: new Date('2024-01-15'),
    },
    {
      reminder_id: 'rem-3',
      property_id: 'property2',
      category: 'maintenance',
      note: 'HVAC filter replacement',
      amount: 0,
      start_date: '2024-03-01',
      repeat_by: 'quarterly',
      status: true,
      created_by: 'user2',
      created_date: new Date('2024-02-01'),
    },
  ]
}

export const generateTestInboxMessages = () => {
  return [
    {
      message_id: 'msg-1',
      message_type: 'task_update',
      message_title: 'Task status updated',
      message_body: 'Your maintenance request has been assigned to a technician.',
      linked_task_id: 'mx_1705276800000',
      created_at: new Date('2024-01-16T09:00:00'),
      is_read: false,
      user_id: 'user1',
    },
    {
      message_id: 'msg-2',
      message_type: 'reminder',
      message_title: 'Rent due soon',
      message_body: 'Rent payment of $2,400 is due in 5 days.',
      linked_task_id: null,
      created_at: new Date('2024-01-26T08:00:00'),
      is_read: true,
      user_id: 'user1',
    },
    {
      message_id: 'msg-3',
      message_type: 'comment',
      message_title: 'New comment on task',
      message_body: 'Mike Tech: Parts have been ordered, ETA 2 days.',
      linked_task_id: 'mx_1708454400000',
      created_at: new Date('2024-02-21T10:00:00'),
      is_read: false,
      user_id: 'user2',
    },
    {
      message_id: 'msg-4',
      message_type: 'system',
      message_title: 'Lease document ready',
      message_body: 'Your signed lease is available in Documents.',
      linked_task_id: null,
      created_at: new Date('2024-01-02T12:00:00'),
      is_read: true,
      user_id: 'user1',
    },
  ]
}

export const generateTestInventoryLists = () => {
  return [
    {
      inventory_id: 'inv-list-1',
      property_id: 'property1',
      unit_id: 'unit-101',
      lease_id: 'lease-1',
      items: [
        { name: 'Refrigerator', condition: 'Good', notes: '' },
        { name: 'Stove', condition: 'Excellent', notes: 'Gas range' },
        { name: 'Dishwasher', condition: 'Good', notes: '' },
      ],
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      inventory_id: 'inv-list-2',
      property_id: 'property2',
      unit_id: 'unit-201',
      lease_id: 'lease-2',
      items: [
        { name: 'Refrigerator', condition: 'Good', notes: 'French door' },
        { name: 'Washer', condition: 'Fair', notes: 'Needs service soon' },
        { name: 'Dryer', condition: 'Good', notes: '' },
      ],
      created_at: new Date('2024-02-01'),
      updated_at: new Date('2024-02-01'),
    },
  ]
}

export const generateTestTasks = (options = {}) => {
  const { status = 'open', priority = 'medium', propertyId = 'property1' } = options
  return [
    {
      task_id: 'task-open-1',
      property_id: propertyId,
      title: 'Leaking faucet',
      description: 'Kitchen sink drips constantly',
      status: status,
      priority: priority,
      task_category: 'plumbing',
      created_by: 'user1',
      created_at: new Date('2024-01-15'),
      updated_at: new Date('2024-01-15'),
    },
    {
      task_id: 'task-progress-1',
      property_id: propertyId,
      title: 'AC not cooling',
      description: 'Living room stays warm',
      status: 'in_progress',
      priority: 'high',
      task_category: 'hvac',
      created_by: 'user1',
      created_at: new Date('2024-01-20'),
      updated_at: new Date('2024-01-22'),
    },
    {
      task_id: 'task-resolved-1',
      property_id: propertyId,
      title: 'Broken light fixture',
      description: 'Bathroom light not working',
      status: 'resolved',
      priority: 'low',
      task_category: 'electrical',
      created_by: 'user1',
      created_at: new Date('2024-01-10'),
      updated_at: new Date('2024-01-12'),
    },
  ]
}

export const generateTestSpCards = () => {
  return [
    {
      sp_card_id: 'spc-1',
      owner_id: 'user2',
      sp_id: 'sp-101',
      sp_name_snapshot: 'FixFast Plumbing',
      owner_note: 'Used for 5 jobs, always on time',
      tags: ['plumbing', 'emergency'],
      created_at: new Date('2024-01-01'),
      updated_at: new Date('2024-01-01'),
    },
    {
      sp_card_id: 'spc-2',
      owner_id: 'user2',
      sp_id: 'sp-102',
      sp_name_snapshot: 'Prime Electric',
      owner_note: 'Licensed, good for complex work',
      tags: ['electrical'],
      created_at: new Date('2024-01-15'),
      updated_at: new Date('2024-01-15'),
    },
  ]
}

/** Aggregates all test data for full fixture generation */
export const generateAllTestData = () => ({
  properties: generateTestProperties(),
  mxRecords: generateTestMxRecords(),
  userRoles: generateTestUserRoles(),
  userProfiles: generateTestUserProfiles(),
  leases: generateTestLeases(),
  transactions: generateTestTransactions(),
  reminders: generateTestReminders(),
  inboxMessages: generateTestInboxMessages(),
  inventoryLists: generateTestInventoryLists(),
  tasks: generateTestTasks(),
  spCards: generateTestSpCards(),
})
